/*
 * GlobContent.AdminServer.Api.Web
 *
 * General API for GlobContent stable content
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BlockchainUserCreateOrUpdate : IEquatable<BlockchainUserCreateOrUpdate>
    { 
        /// <summary>
        /// Gets or Sets BlockchainUserId
        /// </summary>
        [DataMember(Name="blockchainUserId")]
        public string BlockchainUserId { get; set; }

        /// <summary>
        /// Gets or Sets BlockchainPublicKey
        /// </summary>
        [DataMember(Name="blockchainPublicKey")]
        public string BlockchainPublicKey { get; set; }

        /// <summary>
        /// Gets or Sets BlockchainPrivateKey
        /// </summary>
        [DataMember(Name="blockchainPrivateKey")]
        public string BlockchainPrivateKey { get; set; }

        /// <summary>
        /// Gets or Sets BlockchainId
        /// </summary>
        [DataMember(Name="blockchainId")]
        public string BlockchainId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BlockchainUserCreateOrUpdate {\n");
            sb.Append("  BlockchainUserId: ").Append(BlockchainUserId).Append("\n");
            sb.Append("  BlockchainPublicKey: ").Append(BlockchainPublicKey).Append("\n");
            sb.Append("  BlockchainPrivateKey: ").Append(BlockchainPrivateKey).Append("\n");
            sb.Append("  BlockchainId: ").Append(BlockchainId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BlockchainUserCreateOrUpdate)obj);
        }

        /// <summary>
        /// Returns true if BlockchainUserCreateOrUpdate instances are equal
        /// </summary>
        /// <param name="other">Instance of BlockchainUserCreateOrUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BlockchainUserCreateOrUpdate other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BlockchainUserId == other.BlockchainUserId ||
                    BlockchainUserId != null &&
                    BlockchainUserId.Equals(other.BlockchainUserId)
                ) && 
                (
                    BlockchainPublicKey == other.BlockchainPublicKey ||
                    BlockchainPublicKey != null &&
                    BlockchainPublicKey.Equals(other.BlockchainPublicKey)
                ) && 
                (
                    BlockchainPrivateKey == other.BlockchainPrivateKey ||
                    BlockchainPrivateKey != null &&
                    BlockchainPrivateKey.Equals(other.BlockchainPrivateKey)
                ) && 
                (
                    BlockchainId == other.BlockchainId ||
                    BlockchainId != null &&
                    BlockchainId.Equals(other.BlockchainId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BlockchainUserId != null)
                    hashCode = hashCode * 59 + BlockchainUserId.GetHashCode();
                    if (BlockchainPublicKey != null)
                    hashCode = hashCode * 59 + BlockchainPublicKey.GetHashCode();
                    if (BlockchainPrivateKey != null)
                    hashCode = hashCode * 59 + BlockchainPrivateKey.GetHashCode();
                    if (BlockchainId != null)
                    hashCode = hashCode * 59 + BlockchainId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BlockchainUserCreateOrUpdate left, BlockchainUserCreateOrUpdate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BlockchainUserCreateOrUpdate left, BlockchainUserCreateOrUpdate right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
