apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: payglx-admin-api
  name: payglx-admin-api
spec:
  ports:
  - name: payglx-admin-api-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    component: payglx-admin-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}