apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    component: rinadiet-api
  name: rinadiet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rinadiet-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: rinadiet-api
    spec:
      containers:
      - env:
        image: www.payglx.com:5132/rinadiet-api:latest
        args: ["--urls", "http://*:5000"]
        imagePullPolicy: Always
        name: rinadiet-api
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}