apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: rinadiet-api
  name: rinadiet-api
spec:
  ports:
  - name: rinadiet-api-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    component: rinadiet-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}